Blocking strategy
HoudiniGraphql/houdini pull request #1016
Opened 2023-03-22 14:21 UTC by jycouet

Fixes #1013

Reminder: 
- [ ] if throwOnError includes all or query, blocking needs to be true
- [ ] add in config: default blocking strategy
- [ ] add directives `@blocking` `@no_blocking`
- [ ] add a warning if a config is "wrong"
  - [ ] having a throwOnError(all|query) & default blocking is set to false
  - [ ] Just document that `@blocking_false` will never throwOnError
- [ ] update doc query/manual-loading/last chapter about load & result section

### To help everyone out, please make sure your PR does the following:

- [ ] Update the first line to point to the ticket that this PR fixes
- [ ] Add a message that clearly describes the fix
- [ ] If applicable, add a test that would fail without this fix
- [ ] Make sure the unit and integration tests pass locally with `pnpm run tests` and `cd integration && pnpm run tests`
- [ ] Includes a changeset if your fix affects the user with `pnpm changeset`

2023-03-23 09:08 UTC, AlecAivazis requested changes

2023-03-23 17:04 UTC, AlecAivazis requested changes

2023-03-23 17:04 UTC, AlecAivazis commented on packages/houdini/src/codegen/generators/artifacts/index.ts
> +						if (config.defaultBlockingMode === 'always_blocking') {
Reminder that this should go into `houdini-svelte`

2023-03-23 17:04 UTC, AlecAivazis commented on packages/houdini/src/runtime/client/documentStore.ts
> +		blocking,
If we check for the conflicting settings inside of the `fetch` method of query store we can avoid adding `blocking` here

2023-03-24 11:50 UTC, jycouet commented on packages/houdini/src/codegen/generators/artifacts/index.ts
> +						if (config.defaultBlockingMode === 'always_blocking') {
We have to keep in mind that, at some point, some frameworks will share some behavior.
For now, I switch it to svelte 💪^^

2023-03-24 13:36 UTC, jycouet commented
😅
```mermaid
flowchart TD
    A(Config) --> AB[blocking]
    A --> AN[no blocking]
    AB --> B(throwOnError settings)
    AN --> B
    B --> BB[blocking]
    B --> BN[no blocking]
    BB --> C(blocking directives)
    BN --> C
    C --> CB[blocking]
    C --> CN[no blocking]
    CB --> D(fetch args)
    CN --> D
    D --> DB[blocking]
    D --> DN[no blocking]
    DB --> E(Need to block?)
    DN --> E
```

2023-03-24 17:59 UTC, AlecAivazis requested changes

2023-03-24 17:59 UTC, AlecAivazis commented on packages/houdini-svelte/src/plugin/artifactData.ts
> +			const operations = document.document.definitions.filter(
Most of this block isn't necessary. The whole point of `graphql.visit` is to do this search for you. The function passed to `Directive` is only called when the visitor encounters a directive: you just have to check if  `node.name.value === config.blockingDirective`.

2023-03-24 17:59 UTC, AlecAivazis commented on packages/houdini-svelte/src/plugin/index.ts
> +	schema({ config }) {
While we're here, can we move the load directives into the plugin (since they're not used by react)

2023-03-24 17:59 UTC, AlecAivazis commented on packages/houdini-svelte/src/plugin/index.ts
> +	defaultBlockingMode?: 'not_always_blocking' | 'always_blocking'
i think `true | false` is a fine value here. Also, can we name it something like `defaultRouteBlocking`?

2023-03-24 17:59 UTC, AlecAivazis commented on packages/houdini/src/codegen/generators/artifacts/index.ts
> +						if (config.defaultBlockingMode === 'always_blocking') {
I think the react bindings are a great example where the equivalent of `@load` is done with framework-specific tools instead of what we do in svelte. We can always bring them back if/when we need them

2023-03-24 17:59 UTC, AlecAivazis commented on packages/houdini-svelte/src/plugin/transforms/kit/load.ts
> -								AST.booleanLiteral(afterLoad || on_error)
This seems strange - was there an issue with passing `false`?

2023-03-24 17:59 UTC, AlecAivazis commented on packages/houdini-svelte/src/plugin/validate.test.ts
> +		documents: [
These tests need 2 documents each so that we verify that we group error messages together

2023-03-24 17:59 UTC, AlecAivazis commented on packages/houdini/src/runtime/client/plugins/throwOnError.ts
> +						(ctx.config.plugins as any)['houdini-svelte']?.defaultBlockingMode ===
`houdini` shouldn't know anything about `houdini-svelte`. Can we move this into the `fetch` method with the actual `blocking` logic?

2023-03-24 17:59 UTC, AlecAivazis commented on packages/houdini/src/runtime/client/index.ts
> +	throwOnError_operations: ThrowOnErrorOperations[]
Can we mark this as `readonly`?

2023-03-24 17:59 UTC, AlecAivazis commented on site/src/routes/api/query/+page.svx
> +- Use the `blocking: true` parameter in the `fetch` method _(you can check the deep dive "Blocking Navigation" bellow)_
We need to add a subsection in the automatic loading section that talks about blocking the generated queries. Maybe we frame it around "Loading States"?

2023-03-24 17:59 UTC, AlecAivazis commented on site/src/routes/api/graphql-magic/+page.svx
> +### `@no_blocking`
I still prefer `@unblocking` (or just `@unblock`/`@block` ). the `_` casing has been reserved for very special cases in the public API so I think we should try to avoid it unless we have a _very_ good reason

2023-03-27 20:57 UTC, jycouet commented on packages/houdini-svelte/src/plugin/index.ts
> +	defaultBlockingMode?: 'not_always_blocking' | 'always_blocking'
With `BlockingMode` it was too open; that's why I had `'not_always_blocking' | 'always_blocking'` _(that I didn't like)_
Narrowing it down makes more sense 👍
`defaultRouteBlocking`? or should we express that it's client-side navigation only?

2023-03-27 21:02 UTC, jycouet commented on packages/houdini-svelte/src/plugin/transforms/kit/load.ts
> -								AST.booleanLiteral(afterLoad || on_error)
Yes, setting `false` explicitly says at args level: "I don't want it", but it shouldn't be the case.
Here, `afterLoad || on_error` we want to explicitly say YES otherwise we don't express anything. Like this `@directives` can overwrite the situation.

=> Locally in a app we can have a different behavior
=> In e2e tests we can do all situations like this

2023-03-27 21:37 UTC, jycouet commented on site/src/routes/api/query/+page.svx
> +- Use the `blocking: true` parameter in the `fetch` method _(you can check the deep dive "Blocking Navigation" bellow)_
And removing the `deep dive: Blocking navigation`? Or in addition?

In the end, the blocking concept (whatever the name) applies in Automatic & Manual.
Should we add a chapter after `Manual Loading` with the name `Loading States`?

2023-03-27 21:42 UTC, jycouet commented on site/src/routes/api/graphql-magic/+page.svx
> +### `@no_blocking`
Let's go with `@unblocking` 👍

2023-03-30 06:34 UTC, AlecAivazis commented on packages/houdini-svelte/src/plugin/index.ts
> +	defaultBlockingMode?: 'not_always_blocking' | 'always_blocking'
I dont think most people really _care_ that it happens one one versus the other. Also, its very possible that one day we start to do something clever on the backend and resolve early if its taking too long

2023-03-30 06:37 UTC, AlecAivazis commented on packages/houdini-svelte/src/plugin/transforms/kit/load.ts
> -								AST.booleanLiteral(afterLoad || on_error)
Ahh okay cool 👍

2023-04-01 06:28 UTC, AlecAivazis commented on packages/houdini/src/codegen/validators/typeCheck.ts
> +function checkBlockingDirectives(config: Config) {
This should also move into `houdini-svelte` (along with `config.blockDirective`).

2023-04-10 04:14 UTC, AlecAivazis commented on packages/houdini/src/runtime/client/plugins/fetch.ts
> +				} catch (error: unknown) {
if the error isn't the correct type, this will never resolve with the error which I dont think is the desired behavior. A user would encounter this error when they fetch something which means that we should treat these errors like normal network requests errors (which can be arrays)

2023-04-10 04:14 UTC, AlecAivazis commented on site/src/routes/api/config/+page.svx
> +- `defaultRouteBlocking` (optional, default: `false`): Specifies whether the client side routing is blocking or not.
```suggestion
- `defaultRouteBlocking` (optional, default: `false`): Specifies the default blocking behavior for client-side navigation. For more information, please visit [this section of the docs](https://houdinigraphql.com/api/query#manual-loading).
```

2023-04-10 04:14 UTC, AlecAivazis commented on packages/houdini-svelte/src/plugin/artifactData.ts
> +	set_blocking?: boolean
Is there a reason to have 2 different keys in the object? They are mutually exclusive, right? Would a single `boolean | undefined` not work?

2023-04-10 14:21 UTC, jycouet commented on packages/houdini/src/runtime/client/plugins/fetch.ts
> +				} catch (error: unknown) {
I removed this.
We will think about this in another PR

2023-04-10 14:28 UTC, jycouet commented on packages/houdini-svelte/src/plugin/artifactData.ts
> +	set_blocking?: boolean
🤔 We can have a load that is blocking or not blocking.
I would say that it's not exactly the same thing.

2023-04-10 14:43 UTC, jycouet commented on packages/houdini/src/codegen/index.ts
> +		error = Array.isArray(e) && e.length === 1 ? e[0] : e
Not sure how to address this.
Why doing something only for testing environment?

Let's speak later

2023-04-14 09:12 UTC, AlecAivazis approved these changes
Nice job!

2023-04-14 09:17 UTC, merged