Centralize JS code parsing/printing mechanism into core
HoudiniGraphql/houdini pull request #1050
Opened 2023-04-11 12:54 UTC by devunt

Fixes #1047

Recast also provides set of parsing JS/TS code functions that built on top of `@babel/parser`. This PR changes JS/TS code parsing mechanism from using `@babel/parser` to using recast's one, so we can get benefit from its [predefined babel options](https://github.com/benjamn/recast/blob/master/parsers/_babel_options.ts).

Since recast expects the same instance is used between parsing and printing, it is required to use the same recast instance among the whole codebase. This PR makes `houdini` package to export the `printJS` function in along with existing `parseJS` function and make plugins to import it when code printing is needed.

Some test snapshots were also updated, as recast now uses its original context to render the resulting code. This wasn't available before as the parsing was done via `@babel/parser`, not recast. The only changes to snapshots are whitespaces and code styles.

### To help everyone out, please make sure your PR does the following:

- [x] Update the first line to point to the ticket that this PR fixes
- [x] Add a message that clearly describes the fix
- [x] If applicable, add a test that would fail without this fix
- [x] Make sure the unit and integration tests pass locally with `pnpm run tests` and `cd integration && pnpm run tests`
- [x] Includes a changeset if your fix affects the user with `pnpm changeset`

2023-04-11 22:26 UTC, AlecAivazis requested changes

2023-04-11 22:26 UTC, AlecAivazis commented on packages/houdini/src/lib/index.ts
> +export * as recast from 'recast'
I'm not a huge fan of exporting `recast` from the core houdini module just to save the one import line. Especially since it's very likely I will forget 😅 

I think if we were thinking about abstracting the `recast` dependency away from the rest of the codebase I think it would make sense exported as a different name (something I wouldn't be opposed to exploring in a separate PR) but as it is now, I don't think there's a lot of value added to justify the cost of confusing people who aren't confident about the difference.

2023-04-12 04:34 UTC, devunt commented on packages/houdini/src/lib/index.ts
> +export * as recast from 'recast'
As like stated in the PR description, this has to be done because `recast` expects that the same instance is used between its `parse` and `print` function. Plugins were using `parseJS` from the houdini core, and used their own instance of `recast` to `print` it to the actual code, which would raise an error in `print`.

Btw, I also agree with re-exporting whole `recast` from the houdini core is not a great idea. I think exporting something like `printJS` would be more appropriate, so making sure the same instance is used between `parse` and `print`, by using corresponding `parseJS` and `printJS` functions from the houdini core.

2023-04-12 04:40 UTC, AlecAivazis commented on packages/houdini/src/lib/index.ts
> +export * as recast from 'recast'
ohhh so sorry I totally missed that in your description. Are we still able to use the AST builders from a different instance? If so, I think adding `printJS` to `lib` is a great solution. If we have to use the builders from the same instance than we probably want to come up with a good name for those too

2023-04-12 05:16 UTC, devunt commented on packages/houdini/src/lib/index.ts
> +export * as recast from 'recast'
Type building is done via `ast-types` package, and they don't have any assertion on instance equality checking (I looked over the code).

Detailed explanation:

The exact problematic line is [here](https://github.com/benjamn/recast/blob/5e6442d2d66bb00af581b8d08b2ac970bd6d4a5c/lib/patcher.ts#L28), which ensures that the `lines` argument are the instance of `Lines` [class](https://github.com/benjamn/recast/blob/5e6442d2d66bb00af581b8d08b2ac970bd6d4a5c/lib/lines.ts#L25) by using `lines instanceof Lines`. They grab `lines` [from passed code's](https://github.com/benjamn/recast/blob/5e6442d2d66bb00af581b8d08b2ac970bd6d4a5c/lib/patcher.ts#L172)  `loc.lines` field which [was generated by](https://github.com/benjamn/recast/blob/5e6442d2d66bb00af581b8d08b2ac970bd6d4a5c/lib/parser.ts#L15) `parse` function (`loc` was `undefined` when using `@babel/parser` since they don't populate that field, thus making `recast.print` not trying to validate `loc.lines` at all, but now we have them).

if we call `recast.parse` and `recast.print` from different packages, even if they are on the same version, bundler treats it differently and creates two identical `Lines` class which will be like `class Lines_1` and `class Lines_2`, effectively making `parse` returns the object with `Line_1` and `print` try to validate that the object is instance of `Line_2`.

2023-04-12 08:22 UTC, AlecAivazis commented on .changeset/green-camels-walk.md
> +'houdini-svelte': minor
Since this PR doesn't add a new feature to Houdini it should be classified as a `patch`

2023-04-12 08:28 UTC, AlecAivazis commented on packages/houdini-svelte/src/plugin/transforms/componentQuery.test.ts
> +		$: value = _houdini_TestQuery
wow it is silly how happy this change makes me. it always bothered me for absolutely no good reason at all

2023-04-12 08:30 UTC, AlecAivazis requested changes

2023-04-12 08:43 UTC, devunt commented on packages/houdini-svelte/src/plugin/transforms/kit/init.test.ts
My bad. It was serializing the whole parsing result instead of just snapshot-ing the resulting human-readable code. Fixed and snapshots are updated.

2023-04-14 09:18 UTC, AlecAivazis approved these changes

2023-04-14 09:31 UTC, devunt commented
Rebased from `main` due to the conflict introduced by #1016

2023-04-14 09:36 UTC, AlecAivazis approved these changes
Thanks for rebasing!

2023-04-14 09:36 UTC, merged