Reset Cache Functionality
HoudiniGraphql/houdini pull request #1107
Opened 2023-06-17 17:50 UTC by m4tr1k

Fixes issue from this Discord [thread](https://discord.com/channels/1024421016405016718/1118674679440363673/1118674679440363673)

2023-06-20 17:58 UTC, AlecAivazis requested changes

2023-06-20 17:58 UTC, AlecAivazis commented on packages/houdini/src/runtime/cache/tests/reset.test.ts
> +	cache.reset()
I think some of this test is missing. In order to verify that the subscriptions were removed, we just need to call `write` once more and make sure that `set` was never called

2023-06-20 18:48 UTC, m4tr1k commented on packages/houdini/src/runtime/cache/tests/reset.test.ts
> +	cache.reset()
@AlecAivazis Thank you for the review. I'm going to work on it!

2023-06-20 19:16 UTC, AlecAivazis commented on packages/houdini/src/runtime/public/cache.ts
> +	reset(): void {
👍

2023-06-22 06:04 UTC, AlecAivazis approved these changes
Thanks again!!

2023-06-22 06:05 UTC, merged