Bug two subscriptions
HoudiniGraphql/houdini pull request #1123
Opened 2023-07-03 15:02 UTC by Morstis

Fixes a discord bug where you can not subscribe to two subscriptions from the same page.

A workaround was to use different metadatas. 

```
roleUpdates.listen(undefined, { metadata: { subFix: 1 } }).catch(console.error);
roleDeletes.listen(undefined, { metadata: { subFix: 2 } }).catch(console.error);
```

This fixes it by adding more checks if the subscription requests are the same (the artefact name)
The problem was here: https://github.com/HoudiniGraphql/houdini/blob/main/packages/houdini/src/runtime/client/plugins/subscription.ts#L40 

- [x] Update the first line to point to the ticket that this PR fixes
- [x] Add a message that clearly describes the fix
- [x] If applicable, add a test that would fail without this fix
- [x] Make sure the unit and integration tests pass locally with `pnpm run tests` and `cd integration && pnpm run tests`
- [x] Includes a changeset if your fix affects the user with `pnpm changeset`

2023-07-03 17:18 UTC, AlecAivazis requested changes

2023-07-03 17:18 UTC, AlecAivazis commented on .changeset/loud-planets-buy.md
> +'houdini': major
This is actually a `patch` change since there isn't any new features or breaking APIs

2023-07-03 18:19 UTC, Morstis commented on .changeset/loud-planets-buy.md
> +'houdini': major
Ah your right. Fixed it

2023-07-06 07:12 UTC, AlecAivazis submitted a review, later dismissed
Thanks again!

2023-07-06 07:22 UTC, AlecAivazis approved these changes

2023-07-06 07:22 UTC, merged