Houdini 356
HoudiniGraphql/houdini pull request #1265
Opened 2024-02-20 19:13 UTC by MattiasMartens

Fixes #356

Implement the policy "NoCache", mirroring Apollo, which serves a request without reading from or writing to the cache.

Tests are failing for me locally with messages like this:

```
TypeError: Cannot read properties of undefined (reading 'on')
 ❯ vitest.setup.ts:12:1
     10| process.env.HOUDINI_TEST = 'true'
     11| 
     12| beforeEach(clearMock)
       | ^
     13| 
     14| const config = testConfig()
```

This happens even without my changes, but it means I'm not able to write tests for the change.

### To help everyone out, please make sure your PR does the following:

- [X] Update the first line to point to the ticket that this PR fixes
- [X] Add a message that clearly describes the fix
~~- [ ] If applicable, add a test that would fail without this fix
~~- [ ] Make sure the unit and integration tests pass locally with `pnpm run tests` and `cd integration && pnpm run tests`
- [X ] Includes a changeset if your fix affects the user with `pnpm changeset`

2024-02-21 17:09 UTC, AlecAivazis requested changes
Changes look mostly good! Should be able to merge this in soon.

2024-02-21 17:09 UTC, AlecAivazis commented on packages/houdini/src/runtime/client/documentStore.ts
> +			// FINDME whatever calls this is what will decide whether/how to cache it.
I'm a bit confused what the FINDME comments are referring to here. the caching logic should be totally confined to the `cache` plugin

2024-02-21 17:32 UTC, MattiasMartens commented on packages/houdini/src/runtime/client/documentStore.ts
> +			// FINDME whatever calls this is what will decide whether/how to cache it.
Oh no! Trivial mistake on my part. Those were notes I left as I navigated the code. I will remove them.

2024-02-21 17:38 UTC, MattiasMartens commented
@AlecAivazis Great! Test snapshots are now updated.

2024-02-21 20:52 UTC, SeppahBaws reviewed
Should we maybe also add a unit test to ensure that we're 100% certain it doesn't write to the cache?

2024-02-21 20:52 UTC, SeppahBaws commented on packages/houdini/src/codegen/transforms/schema.ts
> +  ${CachePolicy.NoCache}
pretty sure this line will fail the formatting check, due to mismatching indentations
`pnpm format` should do the trick 🙂

2024-02-21 20:53 UTC, MattiasMartens commented
@SeppahBaws As I said above, I am not able to write or run tests for this branch! I get this error for most tests:

```
TypeError: Cannot read properties of undefined (reading 'on')
 ❯ vitest.setup.ts:12:1
     10| process.env.HOUDINI_TEST = 'true'
     11| 
     12| beforeEach(clearMock)
       | ^
     13| 
     14| const config = testConfig()
```

2024-02-21 20:57 UTC, SeppahBaws commented
@MattiasMartens yes of course, was more of a question in general :)
I can take a look at writing a test when I have some spare time, or maybe @AlecAivazis can if he can find the time before I do.

2024-02-23 08:40 UTC, AlecAivazis commented
I had a few moments tonight so I pushed up a test 👍

2024-02-23 08:46 UTC, AlecAivazis approved these changes
Thanks for the contribution!

2024-02-23 08:47 UTC, merged