Add JSDoc comments generation in $result types and enum declarations
HoudiniGraphql/houdini pull request #1277
Opened 2024-03-04 12:45 UTC by gwennlbh

Fixes #1274

It also adds `@deprecated` jsdoc tags when a field has a `deprecationReason`.

I'm not sure about how to write tests. I added a new page under e2e/kit and updated some tests, but only the generation of jsdoc comments on enum declarations is tested.

The new +page.svelte demonstrates that this works!

![image](https://github.com/HoudiniGraphql/houdini/assets/39094199/1287d5e6-9eba-48c5-844a-1a19375151bb)

All tests still pass (on my machine at least)

### To help everyone out, please make sure your PR does the following:

- [x] Update the first line to point to the ticket that this PR fixes
- [x] Add a message that clearly describes the fix
- [x] If applicable, add a test that would fail without this fix
- [x] Make sure the unit and integration tests pass locally with `pnpm run tests` and `cd integration && pnpm run tests`
- [x] Includes a changeset if your fix affects the user with `pnpm changeset`

2024-03-04 13:26 UTC, ewen-lbh commented
I could also generate jsdoc on $input types when I think about it. And I guess adding a couple snapshot tests wouldn't hurt. Leaving this in draft until both of those tasks are done

2024-03-08 12:03 UTC, ewen-lbh commented
I added a snapshot test for jsdoc generation on artifacts types. All unit tests pass. e2e test fail locally but I suspect that I'm missing some setup (I tried `cd e2e/kit && pnpm run tests`, since `integration/` doesn't exist). Testing manually in e2e/kit works anyway, and end-to-end tests pass in CI so I guess it's okay.

2024-03-08 12:05 UTC, ewen-lbh commented
Last thing missing is maybe some documentation. I don't really know where to mention it in the docs though.

2024-03-08 12:28 UTC, SeppahBaws requested changes
Looks good overall, just some small notes 👍

2024-03-08 12:28 UTC, SeppahBaws commented on .changeset/quick-experts-rest.md
> +'houdini': minor
We're not 100% following the semantic versioning - we usually add new features in the patch versions

```suggestion
'houdini': patch
```

2024-03-08 12:28 UTC, SeppahBaws commented on e2e/kit/src/routes/description/+page.gql
I think this e2e test can be removed, since it's being tested in the `houdini` package itself already

2024-03-08 12:44 UTC, SeppahBaws approved these changes
Awesome, thanks for the contribution!

2024-03-08 13:00 UTC, merged