Bump GraphQL to v16
HoudiniGraphql/houdini pull request #1348
Opened 2024-09-04 15:48 UTC by radiden

Fixes #1252

2024-09-04 18:00 UTC, SeppahBaws commented
Thanks for taking the time to look into this!

It looks like the houdini-2.0 branch was out of date with main before you created this PR, which is causing github to be very confused. Could you try rebasing your changes off the latest commit on the houdini-2.0 branch?

2024-09-05 03:59 UTC, AlecAivazis commented
i updated the houdini branch earlier today. i think this branch contains the commits but it shouldn't cause any issues, unless im missing something?

2024-09-05 04:57 UTC, AlecAivazis requested changes

2024-09-05 04:57 UTC, AlecAivazis commented on packages/houdini/src/codegen/transforms/paginate.ts
> +			...(defaultValue
Can we go back to the `if(defaultValue)` structure? the ternary here is a bit hard to read imo

2024-09-10 20:41 UTC, AlecAivazis approved these changes
Thanks for pushing on this!

2024-10-21 18:56 UTC, SeppahBaws commented
Whoops, didn't mean for this to be closed

2024-11-10 18:43 UTC, endigma commented
Superseded by #1387

2024-11-10 19:02 UTC, closed without merging