Implement autoCodeGen vite plugin option
HoudiniGraphql/houdini pull request #1385
Opened 2024-11-09 17:34 UTC by ewen-lbh

### To help everyone out, please make sure your PR does the following:

- [ ] Update the first line to point to the ticket that this PR fixes
- [ ] Add a message that clearly describes the fix
- [ ] If applicable, add a test that would fail without this fix
- [ ] Make sure the unit and integration tests pass locally with `pnpm run tests` and `cd integration && pnpm run tests`
- [ ] Includes a changeset if your fix affects the user with `pnpm changeset`

2024-11-09 18:08 UTC, ewen-lbh commented
Okay, `autoCodeGen: "smart"` works!

The first change in a file site the dev server was started still triggers a reload because we don't know the documents yet, but as the devserver stays up, subsequent changes to the same file only trigger a full-page reload when a graphql document changes!

2024-11-09 18:13 UTC, ewen-lbh commented
I removed my console.logs, but it looks like this:

```sh
# the quiet option for watchAndRun seems to be removed from kitql-watch-and-run...
 Watch-and-Run  ✔ Watch change 100ms
# changeing code in a svelte file
codegen? /home/uwun/projects.local/churros/packages/app/src/routes/(app)/events/[id]/edit/managers/+page.svelte
{
  absolutePath: '/home/uwun/projects.local/churros/packages/app/src/routes/(app)/events/[id]/edit/managers/+page.svelte',
  documents: {
    PageEventEditManager_ManagerUpdates: 'subscription PageEventEditManager_ManagerUpdates($event: LocalID!) {\n' +
      '      event(id: $event) {\n' +
      '        managers {\n' +
      '          user {\n' +
      '            uid\n' +
      '          }\n' +
      '          usedInvite {\n' +
      '            usesLeft\n' +
      '            unusable\n' +
      '          }\n' +
      '          ...PageEventEditManagers_ItemManager\n' +
      '        }\n' +
      '      }\n' +
      '    }',
    AddEventManager: 'mutation AddEventManager($user: UID!, $event: LocalID!, $power: EventManagerPowerLevel!) {\n' +
      '      upsertEventManager(user: $user, event: $event, powerlevel: $power) {\n' +
      '        ... on MutationUpsertEventManagerSuccess {\n' +
      '          data {\n' +
      '            id\n' +
      '            ...List_EventManagers_insert\n' +
      '          }\n' +
      '        }\n' +
      '        ...MutationErrors\n' +
      '      }\n' +
      '    }',
    CreateEventManagerInvite: 'mutation CreateEventManagerInvite(\n' +
      '      $event: LocalID!\n' +
      '      $power: EventManagerPowerLevel!\n' +
      '      $capacity: Capacity!\n' +
      '      $expiresAt: DateTime\n' +
      '    ) {\n' +
      '      upsertEventManagerInvite(\n' +
      '        event: $event\n' +
      '        input: { capacity: $capacity, expiresAt: $expiresAt, powerlevel: $power }\n' +
      '      ) {\n' +
      '        ... on MutationUpsertEventManagerInviteSuccess {\n' +
      '          data {\n' +
      '            id\n' +
      '            ...List_EventManagerInvites_insert @prepend\n' +
      '          }\n' +
      '        }\n' +
      '        ...MutationErrors\n' +
      '      }\n' +
      '    }'
  }
}
Skipped codegen for /home/uwun/projects.local/churros/packages/app/src/routes/(app)/events/[id]/edit/managers/+page.svelte since graphql documents did not change
# changeing a mutation store definition in that same file
 Watch-and-Run  ✔ Watch change 100ms
codegen? /home/uwun/projects.local/churros/packages/app/src/routes/(app)/events/[id]/edit/managers/+page.svelte
{
  absolutePath: '/home/uwun/projects.local/churros/packages/app/src/routes/(app)/events/[id]/edit/managers/+page.svelte',
  documents: {
    PageEventEditManager_ManagerUpdates: 'subscription PageEventEditManager_ManagerUpdates($event: LocalID!) {\n' +
      '      event(id: $event) {\n' +
      '        managers {\n' +
      '          user {\n' +
      '            uid\n' +
      '          }\n' +
      '          usedInvite {\n' +
      '            usesLeft\n' +
      '            unusable\n' +
      '          }\n' +
      '          ...PageEventEditManagers_ItemManager\n' +
      '        }\n' +
      '      }\n' +
      '    }',
    AddEventManager: 'mutation AddEventManager($user: UID!, $event: LocalID!, $power: EventManagerPowerLevel!) {\n' +
      '      upsertEventManager(user: $user, event: $event, powerlevel: $power) {\n' +
      '        ... on MutationUpsertEventManagerSuccess {\n' +
      '          data {\n' +
      '            id\n' +
      '            localID\n' +
      '            ...List_EventManagers_insert\n' +
      '          }\n' +
      '        }\n' +
      '        ...MutationErrors\n' +
      '      }\n' +
      '    }',
    CreateEventManagerInvite: 'mutation CreateEventManagerInvite(\n' +
      '      $event: LocalID!\n' +
      '      $power: EventManagerPowerLevel!\n' +
      '      $capacity: Capacity!\n' +
      '      $expiresAt: DateTime\n' +
      '    ) {\n' +
      '      upsertEventManagerInvite(\n' +
      '        event: $event\n' +
      '        input: { capacity: $capacity, expiresAt: $expiresAt, powerlevel: $power }\n' +
      '      ) {\n' +
      '        ... on MutationUpsertEventManagerInviteSuccess {\n' +
      '          data {\n' +
      '            id\n' +
      '            ...List_EventManagerInvites_insert @prepend\n' +
      '          }\n' +
      '        }\n' +
      '        ...MutationErrors\n' +
      '      }\n' +
      '    }'
  }
}
Regenerating runtime because /home/uwun/projects.local/churros/packages/app/src/routes/(app)/events/[id]/edit/managers/+page.svelte changed
```

2024-11-13 01:03 UTC, AlecAivazis requested changes

2024-11-13 01:03 UTC, AlecAivazis commented on packages/houdini/src/vite/documents.ts
> +export function extractDocuments(source: string): Record<string, string> {
This should rely on a shared function with the [collectDocuments](https://github.com/HoudiniGraphql/houdini/blob/7287f2440f69e58e5f803b1850faeb506f169b42/packages/houdini/src/codegen/index.ts#L207) part of the codegen pipeline. Plugins can define their own logic for what it means to extract a document out of a file and we need to make sure we're picking them up.

2024-11-13 01:03 UTC, AlecAivazis commented on packages/houdini/src/vite/index.ts
> +	const codegen = async (_server: ViteDevServer | undefined, absolutePath: string | null) => {
Can you move this to its own file?

2024-11-13 01:03 UTC, AlecAivazis commented on packages/houdini/src/vite/index.ts
> +					// To prevent full-page reloads every time we change something in a new document, just don't reload.
I think this could be confusing - if the file changes, we should generate. Waiting til a second update will feel clunky if someone is putting a quick demo together where they are copying and pasting entire file contents

2024-11-26 05:32 UTC, AlecAivazis commented
@ewen-lbh any updates here? happy to revisit this when you're ready to see it through

2024-11-26 17:24 UTC, ewen-lbh commented
hi! i'm hoping to get back to it this weekend, exams have been piling up cuz it's almost the end of the semester '^^

2024-12-19 16:38 UTC, AlecAivazis commented
I'm going to close this for now. feel free to re-open this effort when you have time @ewen-lbh

2024-12-19 16:38 UTC, closed without merging

2024-12-21 15:08 UTC, ewen-lbh commented on packages/houdini/src/vite/index.ts
> +					// To prevent full-page reloads every time we change something in a new document, just don't reload.
i was actually on the fence for this, but i think i aggree with you after all haha

2024-12-21 15:17 UTC, ewen-lbh commented on packages/houdini/src/vite/documents.ts
> +export function extractDocuments(source: string): Record<string, string> {
the function is not currently exported -- exporting it is fine i guess?

2024-12-21 15:19 UTC, ewen-lbh commented on packages/houdini/src/vite/documents.ts
> +export function extractDocuments(source: string): Record<string, string> {
also it goes thru every file, whereas i only need a single file, i'll add a variadic arg to specify source locations, tell me if you want it another way (such as breaking up collectDocuments into more functions)

2024-12-21 16:17 UTC, ewen-lbh commented
hiii can you reopen the pr? i committed the changes and verified it works on a real life project ;)

2025-03-04 15:14 UTC, Faroukhamadi commented
Heyy, @AlecAivazis can you reopen the pr ? I'm sure the work from @gwennlbh could help my project massively

2025-03-04 15:36 UTC, SeppahBaws commented
@Faroukhamadi GitHub doesn't let us reopen this PR since its branch was force-pushed or recreated. @gwennlbh will have to create a new PR with their branch.