Bump GraphQL to v16
HoudiniGraphql/houdini pull request #1387
Opened 2024-11-10 18:33 UTC by endigma

Fixes #1252

2024-11-21 14:08 UTC, SeppahBaws requested changes

2024-11-21 16:41 UTC, AlecAivazis commented on .changeset/loud-turtles-study.md
yea i think you're probably right. although I think because we bundle our cli our dependencies aren't actually "real" dependecies, everything is kind of like a dev dependency. but unless we do actually make that move we probably should merge this into the `houdini-2.0` branch

2024-11-22 22:39 UTC, AlecAivazis commented on .changeset/loud-turtles-study.md
i updated the target branch

2024-11-23 01:18 UTC, endigma commented on .changeset/loud-turtles-study.md
I removed `scripts` from the changset

2024-12-03 00:58 UTC, merged