Fix params for component query variable functions
HoudiniGraphql/houdini pull request #295
Opened 2022-05-06 10:18 UTC by fehnomenal

Fixes #188

2022-05-06 10:21 UTC, fehnomenal commented
I use the following typings because no existing type seems to be appropriate:

```ts
export function FooVariables({
    page,
  }: {
    page: { stuff: App.Stuff };
    session: App.Session;
  }): Foo$input {
```

2022-05-06 17:04 UTC, AlecAivazis commented on .changeset/green-dogs-applaud.md
> +'houdini': minor
I believe this is supposed to be a patch, right? I don't see  aren't any API-breaking changes

2022-05-06 17:04 UTC, AlecAivazis commented on src/preprocess/transforms/query.test.ts
> -		    getProps: () => $$props
is `getProps`  not needed for some reason?

2022-05-06 18:16 UTC, fehnomenal commented on src/preprocess/transforms/query.test.ts
> -		    getProps: () => $$props
It is only used in `componentQuery`:

https://github.com/HoudiniGraphql/houdini/blob/f92fdfa8bf612db50073da22d5e50bd176786cf5/src/runtime/query.ts#L212-L239

The commit removes it only for calls to `routeQuery`

2022-05-06 18:16 UTC, fehnomenal commented on .changeset/green-dogs-applaud.md
> +'houdini': minor
Yeah you're right, sorry

2022-05-07 07:45 UTC, AlecAivazis commented on src/preprocess/transforms/query.test.ts
> -		    getProps: () => $$props
Oh, gotcha! Yea the function isn't used in the route queries, I was just leaving it in for simplicity

2022-05-07 07:53 UTC, AlecAivazis requested changes

2022-05-07 07:53 UTC, AlecAivazis commented on src/preprocess/transforms/query.test.ts
> +		import { page, session } from "$app/stores";
These imports aren't valid in sapper or vanilla svelte. Instead you should import `getSession` and friends from `adapter.mjs` like you see [here](https://github.com/HoudiniGraphql/houdini/blob/1cce6a6e0d52a89b41c904b5714685fcbfa5db74/src/runtime/query.ts#L22). I'm actually surprised you needed to add these since I don't see them actually being used in `componentQuery` 🤔

2022-05-07 21:33 UTC, fehnomenal commented on src/preprocess/transforms/query.test.ts
> +		import { page, session } from "$app/stores";
Ah yeah you're right. I will expand the generated adapter. I used `page` and `session` a few lines below by passing the via the `getPage` and `getSession` functions.

2022-05-07 22:06 UTC, fehnomenal commented
Currently, I can only test the kit implementation but I think sapper should work too.

From the code I think the old vanilla cannot work as the function returned `{}` where a store is expected (svelte's `get` calls `store.subscribe()` internally) so this must have failed. Well the last commit adds empty stores to emulate more or less the expected behavior.

2022-05-09 06:35 UTC, AlecAivazis requested changes
One small change and then I think this is good to go! Sorry for submitting these reviews in multiple pieces, it's been a hectic week for me

2022-05-09 06:35 UTC, AlecAivazis commented on src/preprocess/utils/ensureImports.ts
> +	sourceModule: string
making `$houdini` configurable makes sense but i think we can make `$houdini` the default value for `sourceModule` which saves us having to pass it in over and over

2022-05-09 17:44 UTC, fehnomenal commented on src/preprocess/utils/ensureImports.ts
> +	sourceModule: string
No worries, take your time :)

2022-05-10 17:21 UTC, AlecAivazis approved these changes
Looks good! Thanks for being patient

2022-05-10 17:21 UTC, merged