Update init script
HoudiniGraphql/houdini pull request #397
Opened 2022-07-09 23:00 UTC by AlecAivazis

This PR updates the `init` script to ask fewer questions in favor of automatically detecting what tools, framework, module type, etc the project is using

2022-07-09 23:50 UTC, AlecAivazis commented
@david-plugge im curious about your thoughts on this

2022-07-10 00:08 UTC, david-plugge commented
@AlecAivazis looks really nice!
Could you add an option to add the watch-and-run plugin aswell?

2022-07-10 00:55 UTC, AlecAivazis commented
> Could you add an option to add the watch-and-run plugin aswell?

This seems like a reasonable thing to have as part of the default template. I'll check it out

> And why dont you use sveltekits builtin [alias](https://kit.svelte.dev/docs/configuration#alias) instead of configuring them in vite?

Ohh nice! I had NO idea that was a thing 😅 Going to update the script and docs to use this instead

2022-07-10 07:20 UTC, david-plugge commented
That was fast!
One last addition: add npm run generate to the prepare script. I find that really usefull but it is not a must have

2022-07-10 07:31 UTC, AlecAivazis commented
I'm actually struggling to get `watch-and-run` to work with the latest svelte kit - have you seen it work with the new `vite.config.js`?

2022-07-10 08:19 UTC, david-plugge commented
> I'm actually struggling to get `watch-and-run` to work with the latest svelte kit - have you seen it work with the new `vite.config.js`?

i´ve testing a few things and this seems to work:
```js
watchAndRun([
	{
		run: 'npm run generate',
		watch: path.resolve('src/**/*.(graphql|gql|svelte)'),
		delay: 300
	}
])
```
It seems like the plugin doesnt resolve relative paths.

2022-07-10 08:24 UTC, david-plugge commented
And i guess one more [thing](https://github.com/jycouet/kitql/blob/b9ccabd2c11601eda212b925d6b37cb18fb93421/examples/demo1/.graphqlrc.yaml) is missing.

2022-07-11 23:12 UTC, jycouet commented
🔮 Great update 🔮

A few points that I started to list / suggest / pushed:

- [x] adding a default public URL to give idea about the format (with protocol, without saying it)
  - [ ] I put https://countries.trevorblades.com/, but we can have something different
  - [ ] Test if `when: withRunningCheck` url goes to 'http://localhost:3000/api/graphql'
- [x] prevent crash if `vite.config.js` doesn't exist
- [ ] do we need to `generate` at the end?
  - [x] I added a log if there is an error
  - [ ] We will probably have 0 operation at this time. 
  - [ ] When we have 0 operation, we could log it?
- [ ] Adding `$houdini` in `.gitignore`
- [ ] `withRunningCheck` not working 🤔
- [ ] The flow is sometime a bit strange `Welcome` => `Something unexpected` => `Added generate script to package.json`
  - [ ] I'll do some quick workflow tomorrow (drawing ^^)
  - [ ] We have to add flags to `dep` update maybe.

2022-07-16 12:00 UTC, jycouet requested changes
I think that we are getting closer to a perfect `init` 🎉. Nice job @AlecAivazis 💪.

I comment on the PR so that we can speak on the various open points directly (before me mess up everything :p)
So are straightforward to fix; some might need some exchanges.

Let me know how to help 👍

Speak to you soon

2022-07-16 17:26 UTC, AlecAivazis commented on src/cmd/init.ts
> +		tsConfig.compilerOptions.paths = {
this expression does create `path` if it doesn't exist since

2022-07-16 17:40 UTC, AlecAivazis commented on src/cmd/init.ts
> +	await generate(
I'm trying to push users towards never even knowing that there is a generation step. They don't ever have to explicitly run the svelte compiler so I'd like to get to a point where the houdini generator is treated the same. I agree that the error message is very cryptic but we should just fix that in another effort imo instead of introducing a whole new step to cover a situation where someone is running init on an existing houdini project

2022-07-17 14:59 UTC, jycouet approved these changes
🎉 Thx a lot, looks perfect to me 🎉

2022-07-17 16:31 UTC, merged