More powerful fragment masking
HoudiniGraphql/houdini pull request #534
Opened 2022-09-10 19:02 UTC by fehnomenal

Fixes #529

I went ahead and implemented a new argument for the `@houdini` directive and was surprised how easy it was.
`@houdini(mask)` is a nullable boolean and can be used on fragment spreads. Depending on the value the generated types for queries, mutations and nested fragments will have the selection set from the fragment or not.

I added a new config value (`defaultFragmentMasking`) in a backwards compatible way (its value is taken if the `mask` argument is `null` or missing) and deprecated `disableMasking`.

What is missing is the changeset. This is a new feature so semver wise it would be a minor change bringing us to 0.17. What do you think @AlecAivazis ?

### To help everyone out, please make sure your PR does the following:

- [x] Update the first line to point to the ticket that this PR fixes
- [x] Add a message that clearly describes the fix
- [x] If applicable, add a test that would fail without this fix
- [x] Make sure the unit and integration tests pass locally with `pnpm run tests` and `cd integration && pnpm run tests`
- [ ] Includes a changeset if your fix affects the user with `pnpm changeset`

2022-09-12 05:36 UTC, AlecAivazis commented
Awesome! I'll try to find some time in the next few days to take a look 👍 

> This is a new feature so semver wise it would be a minor change bringing us to 0.17

before `1.0` we've been using minor versions to denote breaking changes. features and fixes both are being treated as patch versions until we get that official release. Thanks for checking!

2022-09-12 06:54 UTC, AlecAivazis requested changes
Few small tweaks and this should be good to go 👍

2022-09-12 06:54 UTC, AlecAivazis commented on site/src/routes/api/config.svx
> -- `disableMasking` (optional, default: `false`): A boolean indicating whether fields from referenced fragments should be included in a document's selection set
I agree that the new config value is better but I think we should keep the old one for now just to avoid having a deprecation so soon after breaking so much (fatigue is really real). I think the best bet is to put a note in #459 so we remember to do this as part of the next big release (which it sounds like might be 1.0?? 🤯)

2022-09-12 06:54 UTC, AlecAivazis commented on src/cmd/transforms/schema.ts
> +	mask: Boolean = null
I think having `null` kind of confuses things a little bit since it opens the question of how it's different from passing nothing. We should be able to look at the config value to figure out what the appropriate default is.

2022-09-12 06:54 UTC, AlecAivazis commented on src/cmd/utils/flattenSelections.ts
> +						throw new HoudiniError({
This should be verified in the typecheck validator. If it isn't, then we want to make sure it is checked there since that validator will report multiple errors at once instead of failing on the first. With that in place (and the nullability removed from my earlier comment), it's okay to do `if (maskArgument?.value.kind === "BooleanValue") ...`

2022-09-12 08:41 UTC, fehnomenal commented on src/cmd/transforms/schema.ts
> +	mask: Boolean = null
OK, wow. I was not aware that all arguments in directives seem to be optional even without a default value. Will remove it.

2022-09-12 08:42 UTC, fehnomenal commented on src/cmd/utils/flattenSelections.ts
> +						throw new HoudiniError({
Yes, nice :)

2022-09-12 08:43 UTC, fehnomenal commented on site/src/routes/api/config.svx
> -- `disableMasking` (optional, default: `false`): A boolean indicating whether fields from referenced fragments should be included in a document's selection set
The old config is still available and will be used when the new one is not given. It is not an error but will print a warning to the console. Isn't that a nice middleground?

2022-09-12 08:45 UTC, AlecAivazis commented on site/src/routes/api/config.svx
> -- `disableMasking` (optional, default: `false`): A boolean indicating whether fields from referenced fragments should be included in a document's selection set
Yea, it totally is a good middle ground and If were were at `0.16.5`, I would probably have a different opinion. it just feels not great to have a deprecation warning right after someone has gone through all the trouble to update the other deprecated stuff. And I think `disableMasking` is close enough to reality that it doesn't really justify the potential emotional reaction to having "another thing deprecated"

2022-09-12 09:44 UTC, fehnomenal commented on site/src/routes/api/config.svx
> -- `disableMasking` (optional, default: `false`): A boolean indicating whether fields from referenced fragments should be included in a document's selection set
Alright, I see you. Are you fine with dedeprecating the old config value or do you want me to remove the new one altogether?

2022-09-12 20:34 UTC, AlecAivazis commented on src/cmd/generators/definitions/schema.test.ts
> +		  load: Boolean! = true
We will need to remove the `!` on `load` or else it needs to be specified every time `@houdini` is used which is obviously not what we want.

I just tested this with the following node script:

```javascript
import * as graphql from "graphql";

const schema = graphql.buildSchema(`
    directive @Foo(id: ID!) on FIELD

    type Query { 
        test: Int!
    }
`);

console.log(
  graphql.validate(
    schema,
    graphql.parse(`
        { 
            test @Foo
        }
    `)
  )
);

```

2022-09-12 20:57 UTC, fehnomenal commented on src/cmd/generators/definitions/schema.test.ts
> +		  load: Boolean! = true
With a default value you can omit it. And that's exactly why I was so confused before your other comment on this file.

I thought the semantics are strange if you specify `@houdini(load: null)`. What will happen? Probably nothing as the check is for `!arg.value.value` but it seems a bit fishy to me :shrug:

2022-09-12 21:01 UTC, AlecAivazis commented on src/cmd/generators/definitions/schema.test.ts
> +		  load: Boolean! = true
Okay so what if we do what I originally suggested and have it be non-null with a default pulled from the config value?

```
mask: Boolean! = ${config.disableMasking ? 'false' : 'true'}
```

2022-09-12 22:24 UTC, fehnomenal commented on src/cmd/generators/definitions/schema.test.ts
> +		  load: Boolean! = true
Cool idea :+1: I did it but it messed a bit with the formatting...

2022-09-13 19:49 UTC, AlecAivazis approved these changes
Thanks again!

2022-09-13 19:49 UTC, merged