:sparkles: NEW: mon repo support
HoudiniGraphql/houdini pull request #539
Opened 2022-09-12 19:26 UTC by jycouet

Fixes #536

Looking up for `./node_modules/houdini`

### To help everyone out, please make sure your PR does the following:

- [x] Update the first line to point to the ticket that this PR fixes
- [x] Add a message that clearly describes the fix
- [ ] ~If applicable, add a test that would fail without this fix~
- [ ] ~Make sure the unit and integration tests pass locally with `pnpm run tests` and `cd integration && pnpm run tests`~
- [x] Includes a changeset if your fix affects the user with `pnpm changeset`

2022-09-12 20:40 UTC, AlecAivazis requested changes
🎉

2022-09-12 20:40 UTC, AlecAivazis commented on src/common/fs.ts
> +	return fsExtra.existsSync(dirPath)
We should add something here to use the mock filesystem in tests

2022-09-12 20:40 UTC, AlecAivazis commented on src/common/config.ts
> +	findNodeModulesHoudini(currentLocation: string) {
I think having this as its own public method is a little dangerous since it opens the possibility that someone calls it directly instead of `runtimeSource` which would get around the check for `process.env.TEST`. I think we should either mark this as private or move its logic into `runtimeSource`.

2022-09-12 22:08 UTC, jycouet commented on src/common/config.ts
> +	findNodeModulesHoudini(currentLocation: string) {
Like this?

2022-09-12 22:10 UTC, jycouet commented on src/common/fs.ts
> +	return fsExtra.existsSync(dirPath)
I added the test, but nit sure about it.
Let me know 👍

2022-09-12 22:48 UTC, AlecAivazis commented on src/common/fs.ts
> +	return fsExtra.existsSync(dirPath)
nice! sorry, one last nitpick - can we call the function `existsSync` since it wraps that function in both scenarios?

2022-09-13 07:51 UTC, jycouet commented on src/common/fs.ts
> +	return fsExtra.existsSync(dirPath)
Yep, of course

2022-09-13 08:01 UTC, AlecAivazis approved these changes

2022-09-13 19:50 UTC, merged