feat: Config.exclude can be array
HoudiniGraphql/houdini pull request #559
Opened 2022-09-20 16:27 UTC by DanielHritcu

Fixes #558 

Allow passing an array of strings to `Config.exclude`. Also allow string for this to be a non breaking change.

Should `Config.include` support arrays as well ?

### To help everyone out, please make sure your PR does the following:

- [x] Update the first line to point to the ticket that this PR fixes
- [x] Add a message that clearly describes the fix
- [ ] If applicable, add a test that would fail without this fix
- [ ] Make sure the unit and integration tests pass locally with `pnpm run tests` and `cd integration && pnpm run tests`
- [ ] Includes a changeset if your fix affects the user with `pnpm changeset`

2022-09-20 18:58 UTC, AlecAivazis requested changes
Thanks for submitting this @DanielHritcu! Mind updating the config docs page too?  It lives in [site/src/routes/api/config.svx](https://github.com/HoudiniGraphql/houdini/blob/main/site/src/routes/api/config.svx).

2022-09-20 18:58 UTC, AlecAivazis commented on src/common/config.ts
>  	include: string
Let's make this same change to include too 👍

2022-09-20 19:04 UTC, AlecAivazis commented on src/vite/index.ts
> +					return (
I realize this was there before, but I think we should try to use `config.includeFile` here if possible

2022-09-21 15:56 UTC, DanielHritcu commented on src/common/config.ts
>  	include: string
Will do.

2022-09-23 03:11 UTC, DanielHritcu commented
I added the code for include, but I can't manage to build the integration project to test.

I get this weird error, and can't figure out why it's thrown.

The files get included, and the artifacts generated.

Can be replicated starting here: https://github.com/HoudiniGraphql/houdini/pull/559/commits/f149302df95a2b08277a7ea580ca4979ebc4581d

The error I get:
```
file: /Users/danielhritcu/GitHub/houdini/integration/$houdini/runtime/lib/index.js:5:9
3: export { errorsToGraphQLLayout } from './errors';
4: export * from './types';
5: export * as log from './log';
            ^
6: export * from './deepEquals';
7: // putting this here was the only way i could find to reliably avoid import issues
[WebServer] error during build:
Error: Parse error @:5:10
    at parse$b (file:///Users/danielhritcu/GitHub/houdini/node_modules/.pnpm/vite@3.1.0/node_modules/vite/dist/node/chunks/dep-665b0112.js:33612:355)
    at Object.transform (file:///Users/danielhritcu/GitHub/houdini/node_modules/.pnpm/vite@3.1.0/node_modules/vite/dist/node/chunks/dep-665b0112.js:42799:27)
Error: Process from config.webServer was not able to start. Exit code: 1
```

2022-09-23 20:42 UTC, AlecAivazis commented
@DanielHritcu are you still running into that error?

2022-09-24 04:09 UTC, DanielHritcu commented
@AlecAivazis yes I am.

2022-09-25 06:09 UTC, AlecAivazis commented
Oh, interesting it's happening on github too - alright so it _must_ be related to your changes since these tests ran successfully in your other PR. I'll try to figure out what's going on

2022-09-27 06:42 UTC, AlecAivazis commented
@DanielHritcu I pushed up a few changes that I think have fixed the problem. I'm really not sure how it's any different from what you have but i'm not getting the errors any more. Let me know what you think

2022-10-04 07:25 UTC, AlecAivazis approved these changes

2022-10-04 07:26 UTC, merged