throw if can not import config file
HoudiniGraphql/houdini pull request #563
Opened 2022-09-21 16:37 UTC by DanielHritcu

Fixes #562

Will throw a usable error when the config file is malformed like:

```
Error: Could not load config file at /path-to/houdini.config.js.
Unexpected identifier
     at readConfigFile (file:///Users/danielhritcu/GitHub/houdini/build/vite-esm/index.js:156721:15)
     ...
```

Instead of the generic
```
SyntaxError: Unexpected identifier
    at ESMLoader.moduleStrategy (node:internal/modules/esm/translators:119:18)
    at ESMLoader.moduleProvider (node:internal/modules/esm/loader:469:14)
    at async link (node:internal/modules/esm/module_job:67:21)
```

### To help everyone out, please make sure your PR does the following:

- [x] Update the first line to point to the ticket that this PR fixes
- [x] Add a message that clearly describes the fix
- [ ] If applicable, add a test that would fail without this fix
- [ ] Make sure the unit and integration tests pass locally with `pnpm run tests` and `cd integration && pnpm run tests`
- [ ] Includes a changeset if your fix affects the user with `pnpm changeset`

2022-09-22 15:57 UTC, DanielHritcu commented
I'm having issues running the integration tests, even in the main branch.
I get this error when running `dev` to open the page.
```
[web] fetch failed
[web] TypeError: fetch failed
[web]     at Object.processResponse (/Users/danielhritcu/GitHub/houdini/node_modules/.pnpm/undici@5.10.0/node_modules/undici/lib/fetch/index.js:199:23)
[web]     at /Users/danielhritcu/GitHub/houdini/node_modules/.pnpm/undici@5.10.0/node_modules/undici/lib/fetch/index.js:928:38
[web]     at node:internal/process/task_queues:140:7
[web]     at AsyncResource.runInAsyncScope (node:async_hooks:203:9)
[web]     at AsyncResource.runMicrotask (node:internal/process/task_queues:137:8)
[web]     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
```

Any ideas ?

2022-09-23 05:27 UTC, AlecAivazis requested changes
Thanks for adding this @DanielHritcu! Glad you were able to figure out the issue. I'm not _against_ adding such a warning but i'm not sure where it would exist 🤔

2022-09-23 05:27 UTC, AlecAivazis commented on src/common/config.test.ts
> +describe('loadConfifg', function () {
small typo

2022-09-23 16:26 UTC, DanielHritcu commented
> Thanks for adding this @DanielHritcu! Glad you were able to figure out the issue. I'm not _against_ adding such a warning but i'm not sure where it would exist 🤔

I was thinking that adding `engine-strict=true` to `.npmrc` in the integration folder, also matching the `engines` field to the node version in the github action.

```
# package.json

"engines" : { 
    "node" : "16.17.0"
  }
```

2022-09-23 16:47 UTC, AlecAivazis commented
Okay that sounds good to me until we can find the time to figure out why it's broken on the latest node

2022-09-25 06:02 UTC, AlecAivazis approved these changes
Thanks again!

2022-09-25 06:02 UTC, merged