Feat/lists all
HoudiniGraphql/houdini pull request #693
Opened 2022-11-15 00:31 UTC by jycouet

Fixes #TICKET

### To help everyone out, please make sure your PR does the following:

- [ ] Update the first line to point to the ticket that this PR fixes
- [ ] Add a message that clearly describes the fix
- [ ] If applicable, add a test that would fail without this fix
- [ ] Make sure the unit and integration tests pass locally with `pnpm run tests` and `cd integration && pnpm run tests`
- [ ] Includes a changeset if your fix affects the user with `pnpm changeset`

2022-11-15 00:39 UTC, AlecAivazis requested changes

2022-11-15 00:39 UTC, AlecAivazis commented on packages/houdini/src/codegen/generators/artifacts/operations.ts
> +		if (append && prepend) {
These errors shoud be caught in a validator if possible so that we can report multiple of them at the same time instead of failing on the first. Same for using `@parentID` and `@allLists` together

2022-11-15 00:41 UTC, AlecAivazis commented on packages/houdini/src/codegen/generators/artifacts/artifacts.test.ts
> +		expect(parsedQuery).toMatchInlineSnapshot(`
This test can be simplified  using the custom matcher. The test you copied from was an old one 😅 

```suggestion

		expect(mutationDocs[0]).toMatchInlineSnapshot(`
```

2022-11-15 00:44 UTC, AlecAivazis commented on packages/houdini/src/runtime/lib/config.ts
> +	defaultListAllList?: boolean
This config name is a bit strange to me. Not quite sure what a better alternative is 🤔

2022-11-15 00:51 UTC, AlecAivazis commented on packages/houdini/src/runtime/lib/config.ts
> +	defaultListAllList?: boolean
maybe `config.defaultListTarget: 'all' | null`

2022-11-15 01:51 UTC, jycouet commented on packages/houdini/src/codegen/generators/artifacts/operations.ts
> +		if (append && prepend) {
I moved it to the `typeChecks` and added tests to it.

2022-11-16 08:04 UTC, AlecAivazis approved these changes
Looks good! Thanks again ❤️

2022-11-16 08:05 UTC, merged