Feat/default client
HoudiniGraphql/houdini pull request #738
Opened 2022-12-02 23:10 UTC by jycouet

Fixes #734 #735

### To help everyone out, please make sure your PR does the following:

- [ ] Update the first line to point to the ticket that this PR fixes
- [ ] Add a message that clearly describes the fix
- [ ] If applicable, add a test that would fail without this fix
- [ ] Make sure the unit and integration tests pass locally with `pnpm run tests` and `cd integration && pnpm run tests`
- [ ] Includes a changeset if your fix affects the user with `pnpm changeset`

2022-12-03 00:25 UTC, JacobArrow commented
Looks promising. Great job!

2022-12-05 17:35 UTC, AlecAivazis requested changes

2022-12-05 17:35 UTC, AlecAivazis commented on packages/houdini-svelte/src/plugin/index.ts
> +		const cfgPlugin = plugin_config(cfg)
I'm pretty sure this is a breaking change. The old config used to work if the user provided an extension or not. Can we support both situations here? I guess it's really 4 different cases

2022-12-05 18:21 UTC, AlecAivazis commented on packages/houdini-svelte/src/plugin/index.ts
> +		const cfgPlugin = plugin_config(cfg)
Also, while you're here could you use the async versions of the functions?

2022-12-09 04:21 UTC, AlecAivazis approved these changes

2022-12-09 04:24 UTC, merged