prefix function
HoudiniGraphql/houdini pull request #752
Opened 2022-12-09 17:12 UTC by jycouet

Fixes #751

Since SvelteKit `1.0.0-next.573`, we are not allowed to export non-Kit functions from `+page.js`, or it has to start with "`_`".

### To help everyone out, please make sure your PR does the following:

- [x] Update the first line to point to the ticket that this PR fixes
- [x] Add a message that clearly describes the fix
- [x] If applicable, add a test that would fail without this fix
- [x] Make sure the unit and integration tests pass locally with `pnpm run tests` and `cd integration && pnpm run tests`
- [x] Includes a changeset if your fix affects the user with `pnpm changeset`

2022-12-09 18:17 UTC, AlecAivazis requested changes

2022-12-09 18:17 UTC, AlecAivazis commented on .changeset/swift-bags-dress.md
> +'houdini-svelte': patch
This needs to be a minor

2022-12-09 18:17 UTC, AlecAivazis commented on packages/houdini-svelte/src/plugin/codegen/routes/kit.test.ts
> -		} & BeforeLoadReturn>;
This seems strange - don't we need to include the beforeLoad return values?

2022-12-09 18:17 UTC, AlecAivazis commented on packages/houdini-svelte/src/plugin/codegen/routes/kit.test.ts
> -export type AfterLoadEvent = {
Where did this definition go?

2022-12-09 22:31 UTC, jycouet commented on packages/houdini-svelte/src/plugin/codegen/routes/kit.test.ts
> -		} & BeforeLoadReturn>;
Test was outdated. I think it's better now.

2022-12-09 22:31 UTC, jycouet commented on packages/houdini-svelte/src/plugin/codegen/routes/kit.test.ts
> -export type AfterLoadEvent = {
Test was outdated. I think it's better now.

2022-12-10 16:43 UTC, sjcobb2022 commented
Just a quick comment. Wouldn't this effect #597?

Having the type without the _ prefix prevents the collision.

2022-12-10 16:51 UTC, jycouet commented
> Just a quick comment. Wouldn't this effect/fix #597?
> 
> Having the type without the _ prefix prevents the collision.

Yes, you are right. We will have no more collisions with this fix.

You will be able to do:
```ts
import { FooVariables } from '$houdini'

export const _FooVariables: FooVariables = () => { ...}
```

---

_Just FYI, I will probably continue to use:_
```ts
import { FooVariables as V } from '$houdini'

export const _FooVariables: V = () => { ...}
```
_To have as less "FooVariables" as possible, but I guess that it's only a preference_

2022-12-13 17:42 UTC, AlecAivazis approved these changes

2022-12-13 19:11 UTC, merged