new: plugin global store
HoudiniGraphql/houdini pull request #760
Opened 2022-12-13 22:58 UTC by jycouet

Move global stores to a separate package `houdini-svelte-global-store`

### To help everyone out, please make sure your PR does the following:

- [x] Update the first line to point to the ticket that this PR fixes
- [x] Add a message that clearly describes the fix
- [x] If applicable, add a test that would fail without this fix
- [x] Make sure the unit and integration tests pass locally with `pnpm run tests` and `cd integration && pnpm run tests`
- [x] Includes a changeset if your fix affects the user with `pnpm changeset`

2022-12-13 23:02 UTC, AlecAivazis requested changes

2022-12-13 23:02 UTC, AlecAivazis commented on packages/houdini-svelte/src/plugin/codegen/stores/query.ts
> +export default new ${storeName}()
Let's remove this too while we're at it

2022-12-13 23:08 UTC, AlecAivazis commented on site/src/routes/api/graphql/+page.svx
> +	update.mutate({ variables: { input: MyEnum.Value1 } })
These examples make me think we should make `mutate` a static method? it will still return the value if you want to use it.... what do you think?

2022-12-14 10:22 UTC, jycouet commented on site/src/routes/api/graphql/+page.svx
> +	update.mutate({ variables: { input: MyEnum.Value1 } })
But we would still need `$update.isFetching`
Maybe we can add it in the example to show the purpose of the two steps?

2022-12-14 10:25 UTC, jycouet commented on packages/houdini-svelte/src/plugin/codegen/stores/query.ts
> +export default new ${storeName}()
👍 Done

2022-12-14 10:45 UTC, jycouet commented on packages/houdini-svelte/src/plugin/codegen/stores/query.ts
> +export default new ${storeName}()
Actually not done yet as in transforms we used `default` export.
I'll have a look

2022-12-14 11:14 UTC, jycouet commented on packages/houdini-svelte/src/plugin/codegen/stores/query.ts
> +export default new ${storeName}()
`import GQL_TestQuery from "$houdini/plugins/houdini-svelte/stores/TestQuery";`
is used in 2 places (load): 
- `"artifact": GQL_MyQuery2.artifact`, so I switched to use: `"artifact": _MyQuery2Artifact`
- `const store1 = GQL_MyQuery1;`, so we should have `new MyQuery1()`

In the end `export function store_import` function should not exist as it's using the default!

Maybe we can have a look together later.

2022-12-15 22:36 UTC, jycouet commented on site/src/routes/api/graphql/+page.svx
> +	update.mutate({ variables: { input: MyEnum.Value1 } })
No new MyMutationStore() but 

```
const foo = graphql`

`

foo.mutate()
```

2022-12-15 22:39 UTC, jycouet commented on packages/houdini-svelte/src/plugin/codegen/stores/query.ts
> +export default new ${storeName}()
@AlecAivazis check this plz 🚀

2022-12-17 19:54 UTC, AlecAivazis requested changes

2022-12-17 19:54 UTC, AlecAivazis commented on packages/houdini-svelte/src/plugin/codegen/stores/fragment.ts
>  export default ${storeName}
Reminder to remove this and the other default exports in the typedefs 💥

2022-12-17 22:43 UTC, jycouet commented on packages/houdini-svelte/src/plugin/codegen/stores/fragment.ts
>  export default ${storeName}
Yep, good catch ✅

2022-12-19 04:48 UTC, AlecAivazis approved these changes

2022-12-19 04:49 UTC, merged