Next
HoudiniGraphql/houdini pull request #917
Opened 2023-02-09 17:46 UTC by sjcobb2022

Fixes #916

### To help everyone out, please make sure your PR does the following:

- [x] Update the first line to point to the ticket that this PR fixes
- [x] Add a message that clearly describes the fix
- [x] If applicable, add a test that would fail without this fix
- [x] Make sure the unit and integration tests pass locally with `pnpm run tests` and `cd integration && pnpm run tests`
- [x] Includes a changeset if your fix affects the user with `pnpm changeset`

This should fix everything!

2023-02-09 17:50 UTC, sjcobb2022 commented
There is an error that I missed quickly. let me fix that quickly.

2023-02-09 18:06 UTC, sjcobb2022 commented
@AlecAivazis Should be good to go now!

2023-02-09 18:58 UTC, AlecAivazis requested changes
Thanks for getting this together so quickly! One small tweak and i think it's good go

2023-02-09 18:58 UTC, AlecAivazis commented on packages/houdini-svelte/src/plugin/codegen/routes/index.ts
> +					// .concat(append_loadInput(pageQueries))
Mind cleaning up this comment?

2023-02-10 03:59 UTC, AlecAivazis approved these changes
Thanks!

2023-02-10 03:59 UTC, merged