Svelte: Warn if "include" config key doesn't specify js files
HoudiniGraphql/houdini pull request #939
Opened 2023-02-15 00:05 UTC by luhagel

### To help everyone out, please make sure your PR does the following:

- [ ] Update the first line to point to the ticket that this PR fixes
- [ ] Add a message that clearly describes the fix
- [ ] If applicable, add a test that would fail without this fix
- [x] Make sure the unit and integration tests pass locally with `pnpm run tests` and `cd integration && pnpm run tests`
- [x] Includes a changeset if your fix affects the user with `pnpm changeset`

This PR is the result of a thread @AlecAivazis and I had on discord, where all the generated code was simply *missing* / not there in the first case, which was very difficult to debug on my own.

Now, we throw a warning during the `houdini-svelte` codegen step.

2023-02-15 00:11 UTC, AlecAivazis requested changes

2023-02-15 00:11 UTC, AlecAivazis commented on packages/houdini-svelte/src/plugin/codegen/routes/index.ts
> +				!(config.pluginConfig('houdini-svelte') as HoudiniSvelteConfig).static
Mind tweaking this to use the `plugin_config` utility from [here](https://github.com/HoudiniGraphql/houdini/blob/main/packages/houdini-svelte/src/plugin/kit.ts#L361)? It's really hidden so I don't blame you for not seeing it existed but it will clean this up a bit and apply any defaults

2023-02-15 00:14 UTC, luhagel commented on packages/houdini-svelte/src/plugin/codegen/routes/index.ts
> +				!(config.pluginConfig('houdini-svelte') as HoudiniSvelteConfig).static
Done

2023-02-15 06:50 UTC, AlecAivazis requested changes

2023-02-15 06:50 UTC, AlecAivazis commented on packages/houdini-svelte/src/plugin/codegen/routes/index.ts
> +				!plugin_config(config).static
So even if they don't use any generated load, they still need to have `.js` in their `include` to get session support. So I think something we want something like this:
```suggestion
				// Include path doesn't include js
				!config.include.some((path) => path.includes('js')) &&
				(
				  // And the plugin isn't configured to run in static mode
				  !plugin_config(config).static ||
				  // User uses layout/page queries
				  (uniquePageQueries.length > 0 || uniqueLayoutQueries.length > 0)
				)
```

2023-02-17 06:53 UTC, AlecAivazis approved these changes
Thanks again!

2023-02-17 06:53 UTC, merged