@Paginate two modes
HoudiniGraphql/houdini pull request #958
Opened 2023-02-27 21:43 UTC by jycouet

Fixes #944

New feature: paginate directive now supports a PageByPage mode (in addition to the Infinite one already present)

### To help everyone out, please make sure your PR does the following:

- [x] Update the first line to point to the ticket that this PR fixes
- [x] Add a message that clearly describes the fix
- [x] If applicable, add a test that would fail without this fix
- [x] Make sure the unit and integration tests pass locally with `pnpm run tests` and `cd integration && pnpm run tests`
- [x] Includes a changeset if your fix affects the user with `pnpm changeset`

2023-02-28 04:20 UTC, AlecAivazis requested changes
Nice job! Just a few small comments and it should be good to go 👍

2023-02-28 04:20 UTC, AlecAivazis commented on packages/houdini-svelte/src/runtime/stores/pagination/offset.ts
> +			}
we still want the session passed here. maybe something like:

```suggestion
			const targetFetch = isPageByPage ? parentFetch :  parentFetchUpdate
			await targetFetch({
				variables: queryVariables as _Input,
				fetch,
				metadata,
				policy: isPageByPage ?  artifact.policy : CachePolicy.NetworkOnly,
				session: await getSession(), // Hum?
			})
```

2023-02-28 04:20 UTC, AlecAivazis commented on packages/houdini/src/codegen/generators/definitions/schema.test.ts
> +			enum PaginateMode {
What do you think of Window instead of "PageByPage"? My thinking is that Infinite is also loading page-by-page which makes me think we might want a different word 🤔

2023-02-28 08:04 UTC, jycouet commented on packages/houdini/src/codegen/generators/definitions/schema.test.ts
> +			enum PaginateMode {
Humm, not a big fan of Windows, but I understand the concern.
What I had in mind was the way paginate is displaying the result, not how it's loading it.

2023-03-03 05:19 UTC, AlecAivazis approved these changes

2023-03-03 05:20 UTC, merged