Implement `@required` directive
HoudiniGraphql/houdini pull request #987
Opened 2023-03-12 22:53 UTC by tadeokondrak

Fixes #923

### To help everyone out, please make sure your PR does the following:

- [x] Update the first line to point to the ticket that this PR fixes
- [x] Add a message that clearly describes the fix
- [x] If applicable, add a test that would fail without this fix
- [x] Make sure the unit and integration tests pass locally with `pnpm run tests` and `cd integration && pnpm run tests`
- [x] Includes a changeset if your fix affects the user with `pnpm changeset`

2023-03-13 03:01 UTC, AlecAivazis commented on packages/houdini/src/codegen/generators/artifacts/tests/artifacts.test.ts
> +		                                    "clientNullable": false,
Can you explain the difference between these 2 nullable flags?

2023-03-13 03:01 UTC, AlecAivazis commented
Awesome! Thanks for putting this together 👍

2023-03-14 00:31 UTC, tadeokondrak commented on packages/houdini/src/codegen/generators/artifacts/tests/artifacts.test.ts
> +		                                    "clientNullable": false,
`serverNullable` is set for things that are nullable in the schema. `clientNullable` is always true when `serverNullable` is, but can be false when `@required` is used.

It might be possible to get rid of the distinction but the one piece of code that I left using `serverNullable` (the old value of `nullable`) is here: <https://github.com/tadeokondrak/houdini/blob/d6ceadae172fa0d02b682d48d0141dac6ab67e51/packages/houdini/src/runtime/cache/cache.ts#L321>. I don't understand what it's used for there.

(There's also `bubbleNullability`, which I only use during compile-time. It keeps the code simpler but I might be able to get rid of it and change the code instead.)

2023-03-16 06:12 UTC, AlecAivazis commented
Hopefully that kicks off the tests

2023-03-17 04:15 UTC, AlecAivazis requested changes

2023-03-17 04:15 UTC, AlecAivazis commented on packages/houdini/src/codegen/generators/artifacts/selection.ts
> +					Object.values(fieldObj.selection?.fields ?? {}).some((field) => field.required)
we need to be careful here about the selection since there could be abstract selections to consider. I think it would be best to avoid think about child fields here and instance handle the bubbling when we read values

2023-03-17 17:55 UTC, tadeokondrak commented on packages/houdini/src/codegen/generators/artifacts/selection.ts
> +					Object.values(fieldObj.selection?.fields ?? {}).some((field) => field.required)
Hm, I don't understand. What are abstract selections in this context?

2023-03-17 18:10 UTC, AlecAivazis commented on packages/houdini/src/codegen/generators/artifacts/selection.ts
> +					Object.values(fieldObj.selection?.fields ?? {}).some((field) => field.required)
So right now, the generated artifact has 2 different places where selections are stored: the `fields` object that you found as well as `abstractFields` (another key on that `selection` object). Consider this query:

```
query { 
    node(id: "1") {
        ... on User { 
            parent { 
                name
            }
        }
        
        ... on Animal { 
            parent { 
                name
            }
        }
    }
}
```

Notice that the selection that we have to process depends on the actual type of the object at runtime? That's the reason for the `abstractFields` object: it gives us a type dependent place to hold onto a selection. As you can imagine, there are already a few edge-cases to consider here so I think rather than pushing yet-another-one onto the pile I'd like to see if we can find a way to implement this that keeps the selection logic only local (ie not concerned with other selections in the artifact).

If you're curious, we have to track each selection as a separate object because the actual types of the transient fields can be different (it only matters that the leaf nodes are the same). That is to say, that `parent` could be a different type in each branch.  Otherwise we could just encode `parentType` information

2023-03-17 20:09 UTC, tadeokondrak commented on packages/houdini/src/codegen/generators/typescript/inlineType.ts
> +	forceNonNull,
The typescript code still needs to handle the case described here: https://relay.dev/docs/next/guides/required-directive/#why-are-required-fields-in-an-inline-fragment-still-nullable

2023-03-25 20:26 UTC, tadeokondrak commented on packages/houdini/src/codegen/generators/typescript/inlineType.ts
> +	forceNonNull,
Done

2023-03-25 20:27 UTC, tadeokondrak commented on packages/houdini/src/codegen/generators/artifacts/selection.ts
> +					Object.values(fieldObj.selection?.fields ?? {}).some((field) => field.required)
To match the Relay behaviour this code is still here, but the code now supports abstract fields.

2023-03-27 02:18 UTC, AlecAivazis commented on packages/houdini/src/codegen/generators/typescript/typescript.test.ts
> +	test('@required directive removes nullability from field', async function () {
Thanks for the super thorough tests!!

2023-03-27 02:18 UTC, AlecAivazis commented on packages/houdini/src/runtime/cache/cache.ts
> +				// except when it's an abstract type with @required children - then we return a dummy object
I think im missing something here. Can you explain the situation this is supposed to cover? I'm having a hard time seeing why we can't just enforce that `nullable` is `true` in when we have an abstract type. I'm also a bit confused why abstract types behave differently than normal types in general.

2023-04-01 19:08 UTC, tadeokondrak commented on packages/houdini/src/runtime/cache/cache.ts
> +				// except when it's an abstract type with @required children - then we return a dummy object
So I'm looking into this and it's a bit difficult to reason about this given that it seems that Houdini is already generating incorrect types for cases like the following: (schema lightly modified from e2e/kit)

```graphql
scalar DateTime

type User implements Node {
  id: ID!
  name: String!
  birthDate: DateTime
}

union UserResult = User | Message1

type Message1 {
	message: String!
}

type Query {
  userResult(id: ID!, forceMessage: Boolean!): UserResult!
}
```

```graphql
query ExampleQuery($id: ID!, $forceMessage: Boolean!) {
  userResult(id: $id, forceMessage: $forceMessage) {
    ... on User {
      name
      birthDate
    }
  }
}
```

We get:

```typescript
export type ExampleQuery$result = {
  readonly userResult: {
    readonly __typename: "User";
    readonly name: string;
    readonly birthDate: Date | null;
  };
};
```

This is wrong - if we then use:

```svelte
{#if $GQL_ExampleQuery.data}
  {$GQL_ExampleQuery.data.userResult.birthDate}
{/if}
```

We can get `undefined` displayed if `userResult` was actually a `Message1`. TypeScript thinks that the type of `birthDate` is `Date`, not `Date | undefined`.

The way that we deal with this problem will decide how we should handle similar cases with `@required`.

2023-04-04 18:15 UTC, AlecAivazis commented on packages/houdini/src/runtime/cache/cache.ts
> +				// except when it's an abstract type with @required children - then we return a dummy object
Oh nice catch, I think all we need to do is add `{}` to the generated type for any abstract selection set. Typescript seems to behave correctly: https://www.typescriptlang.org/play?#code/C4TwDgpgBAYg9nKBeKBvKBDAXAZ2AJwEsA7AcygF8oAfNCgKHoGM5i8oAzBZOzHWBIy5wAdBiA

2023-04-04 18:41 UTC, tadeokondrak commented on packages/houdini/src/runtime/cache/cache.ts
> +				// except when it's an abstract type with @required children - then we return a dummy object
Great, I'll do that. Coming back to the original topic of this thread, this code means we can do the same thing (add `{}` as a variant) and not have it be null when we're missing a required field. I could give a more detailed example for that case too.

As far as I understand right now, the code this thread is about is still necessary, but we can remove the `__typename` constant and simply return `{}` when a required field is missing.

2023-04-10 04:52 UTC, tadeokondrak commented on packages/houdini/src/runtime/cache/cache.ts
> +				// except when it's an abstract type with @required children - then we return a dummy object
I've pushed a commit that implements adding `{}` as an option to *non-exhaustive* abstract selections - meaning if you enumerate all possible types of an interface or union you don't need to handle the case of it being none of them. Let me know if you'd prefer the simpler case of always requiring the user to handle `{}`.

But here's an example showing that we can't just use `{}` and we need a dummy __typename like Relay: https://www.typescriptlang.org/play?#code/C4TwDgpgBAYg9nKBeKBvKB9DpIDsCGAthAFxQBEAEvgM4CC5ANFPmTcAE4CWuA5lAF8oAHzQCAUOIDGcXOygAzBMjEsasBJK4KoACiVwAdFhwQCxZEhRVaDAJRpxUZ4oSH84ieNNQAQvg4VdBNwMyJSCmp6JhY2Th5+IVFg7FDzCPIAUi5eXDgOaGAACy4aTPJBSRk5YCgAIwCgoVo-AK0dXQaOY1S8cMtrKPtHF3qA909xIA

Given that, the next commit implements the Relay strategy again.

2023-04-10 05:03 UTC, AlecAivazis commented on packages/houdini/src/runtime/cache/cache.ts
> +				// except when it's an abstract type with @required children - then we return a dummy object
Ahhh yea okay cool that makes total sense. thanks for putting the playground together 👍

2023-04-16 18:27 UTC, AlecAivazis approved these changes

2023-04-16 18:43 UTC, merged